ALTER TABLE users ADD COLUMN theme TEXT DEFAULT 'dark';
ALTER TABLE users ADD COLUMN font_size INTEGER DEFAULT 17;
ALTER TABLE users ADD COLUMN doc_wide_mode BOOLEAN DEFAULT false;
ALTER TABLE users ADD COLUMN timezone TEXT DEFAULT 'UTC+0';
ALTER TABLE users ADD COLUMN date_format TEXT DEFAULT 'MMM D, YYYY';
